# Generated by Django 3.1.7 on 2021-03-02 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateTimeField()),
                ('date_inscription', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('telephone', models.IntegerField()),
                ('cin', models.CharField(max_length=8)),
            ],
        ),
    ]
