# Generated by Django 3.1.7 on 2021-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('dateNaissance', models.DateTimeField()),
                ('telephone', models.IntegerField()),
                ('cin', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
