# Generated by Django 3.1.7 on 2021-03-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210302_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listclients',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='listclients',
            name='dateNaissance',
        ),
        migrations.RemoveField(
            model_name='listclients',
            name='telephone',
        ),
    ]
